//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESolutions.Net {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NetworkAdapterExceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NetworkAdapterExceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESolutions.Net.NetworkAdapterExceptions", typeof(NetworkAdapterExceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The network adapter is no longer able to accept connecition on {0}. See inner exception for further detail..
        /// </summary>
        internal static string AcceptingConnectionsFailed {
            get {
                return ResourceManager.GetString("AcceptingConnectionsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The network adapter already listens to the specified port..
        /// </summary>
        internal static string NetworkAdapterAlreadyListensToTheSpecifiedPort {
            get {
                return ResourceManager.GetString("NetworkAdapterAlreadyListensToTheSpecifiedPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The network adapter is not accepting connections from the port..
        /// </summary>
        internal static string NetworkAdapterIsNotListeningToThisPort {
            get {
                return ResourceManager.GetString("NetworkAdapterIsNotListeningToThisPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during receiving data. Connection is closed..
        /// </summary>
        internal static string ReceivingFailed {
            get {
                return ResourceManager.GetString("ReceivingFailed", resourceCulture);
            }
        }
    }
}
